version: "3.5"

services:
  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  isitfilm:
    build:
      context: .
      dockerfile: Dockerfile
    image: isitfilm:local
    container_name: isitfilm
    command:
      - python
      - IsItFilm.py
    volumes:
      - ./:/usr/src/app
    environment:
      # configuration
      NUM_THREADS: 10
      # database connection
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: isitfilm
