version: "3.5"

services:
  postgresql:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password

  isitfilm:
    build:
      context: .
      dockerfile: Dockerfile
    image: isitfilm:local
    command:
      - python
      - IsItFilm.py
    volumes:
      - ./:/usr/src/app
